const ConfirmedCases = [
    {"id":"1","country_name":"USA","confirmed_case":"1,430,348"},
    {"id":"2","country_name":"Spain","confirmed_case":"271,095"},
    {"id":"3","country_name":"Russia","confirmed_case":"242,271"},
    {"id":"4","country_name":"UK","confirmed_case":"229,705"},
    {"id":"5","country_name":"Italy","confirmed_case":"222,104"},
    {"id":"6","country_name":"Brazil","confirmed_case":"190,137"},
    {"id":"7","country_name":"France","confirmed_case":"178,060"},
    {"id":"8","country_name":"Germany","confirmed_case":"174,098"},
    {"id":"9","country_name":"Turkey","confirmed_case":"143,114"},
    {"id":"10","country_name":"Iran","confirmed_case":"112,725"},
    {"id":"11","country_name":"China","confirmed_case":"82,929"},
    {"id":"12","country_name":"India","confirmed_case":"78,055"},
    {"id":"13","country_name":"Peru","confirmed_case":"76,306"},
    {"id":"14","country_name":"Canada","confirmed_case":"72,278"},
    {"id":"15","country_name":"Belgium","confirmed_case":"53,981"},
    {"id":"16","country_name":"Saudi Arabia","confirmed_case":"44,830"},
    {"id":"17","country_name":"Netherlands","confirmed_case":"43,211"},
    {"id":"18","country_name":"Mexico","confirmed_case":"40,186"},
    {"id":"19","country_name":"Pakistan","confirmed_case":"35,788"},
    {"id":"20","country_name":"Chile","confirmed_case":"34,381"},
    {"id":"21","country_name":"Ecuador","confirmed_case":"30,486"},
    {"id":"22","country_name":"Switzerland","confirmed_case":"30,413"},
    {"id":"23","country_name":"Portugal","confirmed_case":"28,132"},
    {"id":"24","country_name":"Sweden","confirmed_case":"27,909"},
    {"id":"25","country_name":"Qatar","confirmed_case":"26,539"},
    {"id":"26","country_name":"Belarus","confirmed_case":"25,825"},
    {"id":"27","country_name":"Singapore","confirmed_case":"25,346"},
    {"id":"28","country_name":"Ireland","confirmed_case":"23,401"},
    {"id":"29","country_name":"UAE","confirmed_case":"20,386"},
    {"id":"30","country_name":"Bangladesh","confirmed_case":"17,822"},
    {"id":"31","country_name":"Poland","confirmed_case":"17,204"},
    {"id":"32","country_name":"Israel","confirmed_case":"16,548"},
    {"id":"33","country_name":"Ukraine","confirmed_case":"16,425"},
    {"id":"34","country_name":"Japan","confirmed_case":"16,049"},
    {"id":"35","country_name":"Romania","confirmed_case":"16,002"},
    {"id":"36","country_name":"Austria","confirmed_case":"15,997"},
    {"id":"37","country_name":"Indonesia","confirmed_case":"15,438"},
    {"id":"38","country_name":"Colombia","confirmed_case":"12,930"},
    {"id":"39","country_name":"South Africa","confirmed_case":"12,074"},
    {"id":"40","country_name":"Philippines","confirmed_case":"11,618"},
    {"id":"41","country_name":"Dominican Republic","confirmed_case":"11,196"},
    {"id":"42","country_name":"Kuwait","confirmed_case":"11,028"},
    {"id":"43","country_name":"S. Korea","confirmed_case":"10,991"},
    {"id":"44","country_name":"Denmark","confirmed_case":"10,667"},
    {"id":"45","country_name":"Egypt","confirmed_case":"10,431"},
    {"id":"46","country_name":"Serbia","confirmed_case":"10,295"},
    {"id":"47","country_name":"Panama","confirmed_case":"8,944"},
    {"id":"48","country_name":"Czechia","confirmed_case":"8,269"},
    {"id":"49","country_name":"Norway","confirmed_case":"8,175"},
    {"id":"50","country_name":"Australia","confirmed_case":"6,989"},
    {"id":"51","country_name":"Argentina","confirmed_case":"6,879"},
    {"id":"52","country_name":"Malaysia","confirmed_case":"6,779"},
    {"id":"53","country_name":"Morocco","confirmed_case":"6,512"},
    {"id":"54","country_name":"Algeria","confirmed_case":"6,253"},
    {"id":"55","country_name":"Finland","confirmed_case":"6,054"},
    {"id":"56","country_name":"Bahrain","confirmed_case":"5,816"},
    {"id":"57","country_name":"Kazakhstan","confirmed_case":"5,417"},
    {"id":"58","country_name":"Ghana","confirmed_case":"5,408"},
    {"id":"59","country_name":"Moldova","confirmed_case":"5,406"},
    {"id":"60","country_name":"Afghanistan","confirmed_case":"5,226"},
    {"id":"61","country_name":"Nigeria","confirmed_case":"4,971"},
    {"id":"62","country_name":"Oman","confirmed_case":"4,019"},
    {"id":"63","country_name":"Luxembourg","confirmed_case":"3,904"},
    {"id":"64","country_name":"Armenia","confirmed_case":"3,718"},
    {"id":"65","country_name":"Hungary","confirmed_case":"3,341"},
    {"id":"66","country_name":"Bolivia","confirmed_case":"3,148"},
    {"id":"67","country_name":"Iraq","confirmed_case":"3,032"},
    {"id":"68","country_name":"Thailand","confirmed_case":"3,017"},
    {"id":"69","country_name":"Cameroon","confirmed_case":"2,800"},
    {"id":"70","country_name":"Greece","confirmed_case":"2,760"},
    {"id":"71","country_name":"Azerbaijan","confirmed_case":"2,758"},
    {"id":"72","country_name":"Uzbekistan","confirmed_case":"2,612"},
    {"id":"73","country_name":"Guinea","confirmed_case":"2,374"},
    {"id":"74","country_name":"Honduras","confirmed_case":"2,255"},
    {"id":"75","country_name":"Croatia","confirmed_case":"2,213"},
    {"id":"76","country_name":"Bosnia and Herzegovina","confirmed_case":"2,181"},
    {"id":"77","country_name":"Senegal","confirmed_case":"2,105"},
    {"id":"78","country_name":"Bulgaria","confirmed_case":"2,069"},
    {"id":"79","country_name":"Ivory Coast","confirmed_case":"1,912"},
    {"id":"80","country_name":"Sudan","confirmed_case":"1,818"},
    {"id":"81","country_name":"Cuba","confirmed_case":"1,810"},
    {"id":"82","country_name":"Iceland","confirmed_case":"1,802"},
    {"id":"83","country_name":"Estonia","confirmed_case":"1,751"},
    {"id":"84","country_name":"North Macedonia","confirmed_case":"1,694"},
    {"id":"85","country_name":"Lithuania","confirmed_case":"1,505"},
    {"id":"86","country_name":"New Zealand","confirmed_case":"1,497"},
    {"id":"87","country_name":"Slovakia","confirmed_case":"1,469"},
    {"id":"88","country_name":"Slovenia","confirmed_case":"1,463"},
    {"id":"89","country_name":"Guatemala","confirmed_case":"1,342"},
    {"id":"90","country_name":"Djibouti","confirmed_case":"1,268"},
    {"id":"91","country_name":"Somalia","confirmed_case":"1,219"},
    {"id":"92","country_name":"DRC","confirmed_case":"1,169"},
    {"id":"93","country_name":"Mayotte","confirmed_case":"1,143"},
    {"id":"94","country_name":"Hong Kong","confirmed_case":"1,051"},
    {"id":"95","country_name":"Kyrgyzstan","confirmed_case":"1,044"},
    {"id":"96","country_name":"El Salvador","confirmed_case":"1,037"},
    {"id":"97","country_name":"Tunisia","confirmed_case":"1,032"},
    {"id":"98","country_name":"Gabon","confirmed_case":"1,004"},
    {"id":"99","country_name":"Maldives","confirmed_case":"955"},
    {"id":"100","country_name":"Latvia","confirmed_case":"951"},
    {"id":"101","country_name":"Sri Lanka","confirmed_case":"915"},
    {"id":"102","country_name":"Cyprus","confirmed_case":"905"},
    {"id":"103","country_name":"Albania","confirmed_case":"880"},
    {"id":"104","country_name":"Lebanon","confirmed_case":"878"},
    {"id":"105","country_name":"Niger","confirmed_case":"860"},
    {"id":"106","country_name":"Guinea-Bissau","confirmed_case":"836"},
    {"id":"107","country_name":"Costa Rica","confirmed_case":"815"},
    {"id":"108","country_name":"Tajikistan","confirmed_case":"801"},
    {"id":"109","country_name":"Burkina Faso","confirmed_case":"773"},
    {"id":"110","country_name":"Andorra","confirmed_case":"760"},
    {"id":"111","country_name":"Mali","confirmed_case":"758"},
    {"id":"112","country_name":"Paraguay","confirmed_case":"740"},
    {"id":"113","country_name":"Kenya","confirmed_case":"737"},
    {"id":"114","country_name":"Uruguay","confirmed_case":"719"},
    {"id":"115","country_name":"Diamond Princess","confirmed_case":"712"},
    {"id":"116","country_name":"Georgia","confirmed_case":"647"},
    {"id":"117","country_name":"San Marino","confirmed_case":"643"},
    {"id":"118","country_name":"Jordan","confirmed_case":"582"},
    {"id":"119","country_name":"Channel Islands","confirmed_case":"548"},
    {"id":"120","country_name":"Equatorial Guinea","confirmed_case":"522"},
    {"id":"121","country_name":"Tanzania","confirmed_case":"509"},
    {"id":"122","country_name":"Jamaica","confirmed_case":"509"},
    {"id":"123","country_name":"Malta","confirmed_case":"508"},
    {"id":"124","country_name":"Zambia","confirmed_case":"446"},
    {"id":"125","country_name":"Taiwan","confirmed_case":"440"},
    {"id":"126","country_name":"Réunion","confirmed_case":"439"},
    {"id":"127","country_name":"Venezuela","confirmed_case":"423"},
    {"id":"128","country_name":"Sierra Leone","confirmed_case":"387"},
    {"id":"129","country_name":"Palestine","confirmed_case":"375"},
    {"id":"130","country_name":"Chad","confirmed_case":"372"},
    {"id":"131","country_name":"Congo","confirmed_case":"333"},
    {"id":"132","country_name":"Isle of Man","confirmed_case":"332"},
    {"id":"133","country_name":"Mauritius","confirmed_case":"332"},
    {"id":"134","country_name":"Benin","confirmed_case":"327"},
    {"id":"135","country_name":"Montenegro","confirmed_case":"324"},
    {"id":"136","country_name":"Cabo Verde","confirmed_case":"289"},
    {"id":"137","country_name":"Vietnam","confirmed_case":"288"},
    {"id":"138","country_name":"Rwanda","confirmed_case":"287"},
    {"id":"139","country_name":"Ethiopia","confirmed_case":"263"},
    {"id":"140","country_name":"Nepal","confirmed_case":"250"},
    {"id":"141","country_name":"Haiti","confirmed_case":"234"},
    {"id":"142","country_name":"Sao Tome and Principe","confirmed_case":"220"},
    {"id":"143","country_name":"Togo","confirmed_case":"219"},
    {"id":"144","country_name":"Liberia","confirmed_case":"213"},
    {"id":"145","country_name":"Madagascar","confirmed_case":"212"},
    {"id":"146","country_name":"South Sudan","confirmed_case":"203"},
    {"id":"147","country_name":"Martinique","confirmed_case":"189"},
    {"id":"148","country_name":"Eswatini","confirmed_case":"187"},
    {"id":"149","country_name":"Faeroe Islands","confirmed_case":"187"},
    {"id":"150","country_name":"Myanmar","confirmed_case":"181"},
    {"id":"151","country_name":"Guadeloupe","confirmed_case":"155"},
    {"id":"152","country_name":"French Guiana","confirmed_case":"153"},
    {"id":"153","country_name":"Gibraltar","confirmed_case":"147"},
    {"id":"154","country_name":"CAR","confirmed_case":"143"},
    {"id":"155","country_name":"Brunei","confirmed_case":"141"},
    {"id":"156","country_name":"Uganda","confirmed_case":"139"},
    {"id":"157","country_name":"Cambodia","confirmed_case":"122"},
    {"id":"158","country_name":"Bermuda","confirmed_case":"121"},
    {"id":"159","country_name":"Trinidad and Tobago","confirmed_case":"116"},
    {"id":"160","country_name":"Guyana","confirmed_case":"113"},
    {"id":"161","country_name":"Mozambique","confirmed_case":"104"},
    {"id":"162","country_name":"Aruba","confirmed_case":"101"},
    {"id":"163","country_name":"Monaco","confirmed_case":"96"},
    {"id":"164","country_name":"Bahamas","confirmed_case":"94"},
    {"id":"165","country_name":"Cayman Islands","confirmed_case":"86"},
    {"id":"166","country_name":"Barbados","confirmed_case":"85"},
    {"id":"167","country_name":"Liechtenstein","confirmed_case":"82"},
    {"id":"168","country_name":"Sint Maarten","confirmed_case":"76"},
    {"id":"169","country_name":"Yemen","confirmed_case":"70"},
    {"id":"170","country_name":"Libya","confirmed_case":"64"},
    {"id":"171","country_name":"Malawi","confirmed_case":"63"},
    {"id":"172","country_name":"French Polynesia","confirmed_case":"60"},
    {"id":"173","country_name":"Syria","confirmed_case":"48"},
    {"id":"174","country_name":"Angola","confirmed_case":"45"},
    {"id":"175","country_name":"Macao","confirmed_case":"45"},
    {"id":"176","country_name":"Mongolia","confirmed_case":"42"},
    {"id":"177","country_name":"Saint Martin","confirmed_case":"39"},
    {"id":"178","country_name":"Eritrea","confirmed_case":"39"},
    {"id":"179","country_name":"Zimbabwe","confirmed_case":"37"},
    {"id":"180","country_name":"Nicaragua","confirmed_case":"25"},
    {"id":"181","country_name":"Antigua and Barbuda","confirmed_case":"25"},
    {"id":"182","country_name":"Botswana","confirmed_case":"24"},
    {"id":"183","country_name":"Timor-Leste","confirmed_case":"24"},
    {"id":"184","country_name":"Gambia","confirmed_case":"23"},
    {"id":"185","country_name":"Grenada","confirmed_case":"21"},
    {"id":"186","country_name":"Laos","confirmed_case":"19"},
    {"id":"187","country_name":"Belize","confirmed_case":"18"},
    {"id":"188","country_name":"Fiji","confirmed_case":"18"},
    {"id":"189","country_name":"New Caledonia","confirmed_case":"18"},
    {"id":"190","country_name":"Saint Lucia","confirmed_case":"18"},
    {"id":"191","country_name":"St. Vincent Grenadines","confirmed_case":"17"},
    {"id":"192","country_name":"Curaçao","confirmed_case":"16"},
    {"id":"193","country_name":"Dominica","confirmed_case":"16"},
    {"id":"194","country_name":"Namibia","confirmed_case":"16"},
    {"id":"195","country_name":"Mauritania","confirmed_case":"15"},
    {"id":"196","country_name":"Burundi","confirmed_case":"15"},
    {"id":"197","country_name":"Bhutan","confirmed_case":"15"},
    {"id":"198","country_name":"Saint Kitts and Nevis","confirmed_case":"15"},
    {"id":"199","country_name":"Falkland Islands","confirmed_case":"13"},
    {"id":"200","country_name":"Turks and Caicos","confirmed_case":"12"},
    {"id":"201","country_name":"Vatican City","confirmed_case":"12"},
    {"id":"202","country_name":"Comoros","confirmed_case":"11"},
    {"id":"203","country_name":"Montserrat","confirmed_case":"11"},
    {"id":"204","country_name":"Greenland","confirmed_case":"11"},
    {"id":"205","country_name":"Seychelles","confirmed_case":"11"},
    {"id":"206","country_name":"Suriname","confirmed_case":"10"},
    {"id":"207","country_name":"MS Zaandam","confirmed_case":"9"},
    {"id":"208","country_name":"Papua New Guinea","confirmed_case":"8"},
    {"id":"209","country_name":"British Virgin Islands","confirmed_case":"7"},
    {"id":"210","country_name":"Caribbean Netherlands","confirmed_case":"6"},
    {"id":"211","country_name":"St. Barth","confirmed_case":"6"},
    {"id":"212","country_name":"Western Sahara","confirmed_case":"6"},
    {"id":"213","country_name":"Anguilla","confirmed_case":"3"},
    {"id":"214","country_name":"Lesotho","confirmed_case":"1"},
    {"id":"215","country_name":"Saint Pierre Miquelon","confirmed_case":"1"},
]

module.exports = ConfirmedCases;